server:
  port: 8080

spring:
  application:
    name: service-order
  datasource:
    druid:
      username: root
      password: admin
      url: jdbc:mysql:///test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
  redis:
    host: localhost
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    #    default-property-inclusion: ALWAYS
    #参数意义：
    #    #JsonInclude.Include.ALWAYS              默认
    #    #JsonInclude.Include.NON_DEFAULT     属性为默认值不序列化
    #    #JsonInclude.Include.NON_EMPTY         属性为 空（””） 或者为 NULL 都不序列化
    #    #JsonInclude.Include.NON_NULL           属性为NULL   不序列化
  freemarker:
    suffix: .ftl
    #check-template-location: false
  zipkin:
    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL， 而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
  cloud:
    nacos:
      discovery:
        #server-addr: 127.0.0.1:8848
        server-addr: tj1-b2c-systech-mione-test03.kscn:80
        username: nacos
        password: nacos
    sentinel:
      transport:
        port: 9999 #跟控制台交流的端口,随意指定一个未使用的端口即可
        dashboard: localhost:8090 # 指定控制台服务的地址

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    cn.mmc8102: info
    cn.mmc8102.order.mapper: debug

rocketmq:
  name-server: 127.0.0.1:9876 #rocketMQ服务的地址
  producer:
    group: shop-order # 生产者组

feign:
  sentinel:
    enabled: true


